version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    executor: python/3.12
    steps:
      - checkout
#      - python/install-packages:
#          pkg-manager: pip
#          pip-dependency-file: test-requirements.txt
      - python/test:
          pip-dependency-file: test-requirements.txt
          test-tool: pytest


workflows:
  version: 2
  test:
    jobs:
      - test
